name: Build .Net

on:
  push:
    branches:
      - main
      - rc
      - dev
      - feature/*
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  repository-projects: write

jobs:
  build:
    uses: codedesignplus/workflows/.github/workflows/build-microservice.yaml@main
    with:
      project-name: CodeDesignPlus.Net.Microservice.Licenses
      microservice-name: ms-licenses
      organization: ${{ vars.ORGANIZATION }}
      sonar-server: ${{ vars.SONAR_SERVER }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}